language: scala

sudo: false

scala:
  - 2.12.8
  - 2.13.3

jdk: openjdk10

env:
  global:
    - TRAVIS_NODE_VERSION="4"

script: scripts/travis-build.sh

cache:
  directories:
    - "$HOME/.cache/coursier"
    - "$HOME/.sbt/boot/scala*"
    - "$HOME/.sbt/launchers"
    - "$HOME/.ivy2/cache"
    - "$HOME/.nvm"
